#
# Copyright © Michał Biarda. All rights reserved.
# See LICENSE.txt for license details.
#

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  phpVersion: 7.4

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'

- script: ./vendor/bin/phpunit --no-configuration --log-junit $(System.DefaultWorkingDirectory)/junit-report.xml ./src/Test/Unit/
  displayName: 'Run unit tests with phpunit'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'junit-report.xml'
    failTaskOnFailedTests: true
  displayName: 'Publish unit tests results'

- script: ./vendor/bin/phpcs --standard=./phpcs.ruleset.xml ./src/
  displayName: 'Run PHP code sniffer'

- script: ./vendor/bin/phpmd ./src/ ansi cleancode,codesize,unusedcode,design
  displayName: 'Run PHP mess detector for basic rulesets'

- script: ./vendor/bin/phpmd ./src/ ansi controversial,naming --exclude /Model/*,/Form/*
  displayName: 'Run PHP mess detector for controversial ruleset'